name: Reactive Grid
description: The Reactive Grid Blog

permalink: /:year/:month/:day/:title
paginate: 5
markdown: maruku
pygments: true

exclude: [.bowerrc, Gemfile, Gemfile.lock, gulpfile.*, node_modules, bower.json,
          bower, package.json, README.md]
